version: '3.3'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-backend
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0"
    restart: always
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    ports:
      - 8008:8000
    depends_on:
      - db

  db:
    
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: dbase
    restart: always
    env_file:
      - ./.postgres

volumes:
  pgdata: {}

